#!/bin/sh

info(){
  printf "%s\\n" "$1"
}

usage='xcode-nuke
Delete derived data and spm caches.

usage: xcode-nuke [-h | --help] [-n | --no-spm]

  -h    |   --help    Print this usage documentation and exit
  -n    |   --no-spm  Do not clear spm caches
'

spm=1
case $1 in
  --help|-h)
    info "$usage"
    exit 0
    ;;

  --no-spm|-n)
    spm=0
    shift
    ;;
esac

info "rm ~/Library/Developer/Xcode/DerivedData"
rm -rf ~/Library/Developer/Xcode/DerivedData

if [ "$spm" -eq 1 ]; then
  info "rm ~/Library/Caches/org.swift.swiftpm"
  rm -rf ~/Library/Caches/org.swift.swiftpm

  info "rm ~/Library/org.swift.swiftpm"
  rm -rf ~/library/org.swift.swiftpm
fi
