#!/bin/sh

error(){
  red="\e[1;31m"
  reset="\e[0m"
  printf "${red}%s${reset}\n" "$1"  >&2
}

info(){
  printf "%s\n" "$1"
}

usage='xcode-play
Open a scratch playground with Xcode
Requires a playground to be located at ~/.scratch.playground

usage: xcode-play [-h | --help] [--current | --beta]

  -h | --help           Print this usage documentation and exit

  --current             DEFAULT - Use the currently selected Xcode version.

  --beta                Use the newest beta version of Xcode.
'

version="--current"

case $1 in
  --current)
    shift
    ;;
  --beta)
    version="--beta"
    shift
    ;;
esac

case $1 in
  --current|--beta)
    error "Invalid configuration, can't specify multiple Xcode applications"
    exit 1
    ;;
  --help|-h)
    info "$usage"
    exit 0
    ;;
esac

xcode-open "$version" "$HOME/.scratchpad.playground"
