#!/bin/sh

error(){
  red="\e[1;31m"
  reset="\e[0m"
  printf "${red}%s${reset}\n" "$1"  >&2
}

info(){
  printf "%s\n" "$1"
}

usage='xcode-open
Open a directory with Xcode

usage: xcode-open [-h | --help] [--current | --beta] [PATH]

  -h | --help           Print this usage documentation and exit

  --current             DEFAULT - Use the currently selected Xcode version.

  --beta                Use the newest beta version of Xcode.

  PATH                  The path to the directory containing the Xcode project.
                        If not provided, will default to the current directory.
'

app=$(xcode-version --path)

case $1 in
  --current)
    shift
    ;;
  --beta)
    app=$(xcode-list | sort -r | grep -m 1 'beta')
    shift
    ;;
esac

case $1 in
  --current|--beta)
    error "Invalid configuration, can't specify multiple Xcode applications"
    exit 1
    ;;
  --help|-h)
    info "$usage"
    exit 0
    ;;
esac

target=${1:-"."}

open -a "$app" "$target"
